# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: qiita-auto-update

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ tkoyama010-patch-1 ]
  pull_request:
    branches: [ tkoyama010-patch-1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Get Job URL
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: jobs
    - name: Backup
      run: |
        echo $JOB_ID
        echo $HTML_URL
        echo ${{ steps.jobs.outputs.job_id }}
        echo ${{ steps.jobs.outputs.html_url }}
        python qiita_backupper.py ${ACCOUNT} md
        git config user.name ${NAME}
        git config user.email ${EMAIL}
        git remote set-url origin https://${ACCOUNT}:${{ secrets.GITHUB_PASS }}@github.com/${ACCOUNT}/${REPO}
        git branch
        git checkout tkoyama010-patch-1
        git branch
        git add doc
        git commit --allow-empty -m ":green_heart: JOB_ID $JOB_ID
        HTML_URL $HTML_URL"
        git push origin tkoyama010-patch-1
      env:
        ACCOUNT: tkoyama010
        NAME: "qiita-auto-update"
        EMAIL: "qiita-auto-update"
        REPO: qiita_backupper
        JOB_ID: ${{ steps.jobs.outputs.job_id }}
        HTML_URL: ${{ steps.jobs.outputs.html_url }}
